/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A reference to a recent block, binding a transaction to a fork. */
export declare class BlockRef {
  /** Derive from a 40-character block id, as `head_block_id` gives you. */
  static fromBlockId(blockId: string): BlockRef
  /** Build directly from the two reference fields. */
  static fromParts(refBlockNum: number, refBlockPrefix: number): BlockRef
  get refBlockNum(): number
  get refBlockPrefix(): number
  get blockNum(): number
}

/** A Hive private key. */
export declare class PrivateKey {
  /** Parse a WIF (`5...`) or a 64-character hex scalar. */
  constructor(key: string)
  /** Parse a WIF specifically. Rejects Bitcoin compressed-form (`K`/`L`) keys. */
  static fromWif(wif: string): PrivateKey
  /** Generate a new key from the OS CSPRNG. */
  static generate(): PrivateKey
  /**
   * Derive a key from an account name, role and master password.
   *
   * Hive's master-password scheme: one unsalted SHA-256, no work factor. Weak by
   * construction and provided because account creation defines it, not because it
   * is a good idea. Prefer `fromMnemonic`.
   */
  static fromPassword(account: string, role: string, password: string): PrivateKey
  /** Derive a key from a Graphene brain key and sequence number. */
  static fromBrainKey(phrase: string, sequence?: number | undefined | null): PrivateKey
  /** Derive a Hive role key from a BIP-39 mnemonic, on the BIP-48 path wallets use. */
  static fromMnemonic(mnemonic: string, role: string, accountIndex?: number | undefined | null, keyIndex?: number | undefined | null, passphrase?: string | undefined | null): PrivateKey
  /** Decrypt a BIP-38 `6P...` key. */
  static fromBip38(encrypted: string, passphrase: string): PrivateKey
  /** The matching public key. */
  publicKey(): PublicKey
  /**
   * Export as a WIF string.
   *
   * Named so every disclosure of the secret is visible at the call site. There is
   * deliberately no getter, no `toString` and no `toJSON` that does this for you.
   */
  toWif(): string
  /** Encrypt this key under a passphrase, BIP-38 style. Returns a `6P...` string. */
  toBip38(passphrase: string): string
  /**
   * Sign an arbitrary message — the login-handshake primitive.
   *
   * Returns the 65-byte compact signature as hex.
   */
  signMessage(message: string | Buffer): string
  /** Redacted. See the module docs. */
  toString(): string
  /**
   * Redacted, so `JSON.stringify` cannot leak the key either.
   *
   * The `js_name` matters: JavaScript looks for `toJSON` exactly, and napi's
   * default conversion of `to_json` would give `toJson`, which
   * `JSON.stringify` ignores.
   */
  toJSON(): string
}

/** A Hive public key. */
export declare class PublicKey {
  /** Parse a prefixed key such as `STM7...`. */
  constructor(key: string)
  /** Render with a chain prefix. */
  toStringWithPrefix(prefix?: string | undefined | null): string
  /** The 33-byte compressed encoding, as hex. */
  toHex(): string
  toString(): string
  toJSON(): string
  /** Whether two keys are the same point. */
  equals(other: PublicKey): boolean
}

/**
 * A block reference with an explicit staleness bound.
 *
 * Refresh it from a timer; read it on the signing path. Reading a stale reference
 * throws rather than returning something unusable — signing against an expired one
 * produces a transaction the relay accepts and the chain rejects.
 */
export declare class TaposCache {
  constructor(maxAgeSeconds?: number | undefined | null)
  /** Store a freshly fetched reference. */
  store(blockRef: BlockRef): void
  /** Store from a `head_block_id` string. */
  storeBlockId(blockId: string): void
  /** The cached reference, or a thrown error if it is stale or absent. */
  blockRef(): BlockRef
  /** Whether a usable reference is available right now. */
  isFresh(): boolean
  /** Age of the cached reference in seconds, or `null`. */
  ageSeconds(): number | null
  invalidate(): void
}

/** The result of checking keys against an authority. */
export interface AuthorityCheck {
  /** Whether the matched keys alone meet the threshold. */
  satisfied: boolean
  /** Whether the answer is final, or depends on accounts not looked up. */
  conclusive: boolean
  weight: number
  threshold: number
  shortfall: number
  matchedKeys: Array<string>
  /** Delegations to other accounts, which an offline check cannot follow. */
  unresolvedAccounts: Array<string>
}

/** The chain id this build signs against, as hex. */
export declare function chainId(chain?: string | undefined | null): string

/**
 * Check whether a set of public keys satisfies an authority.
 *
 * `authority` is the shape the API returns:
 * `{weight_threshold, account_auths, key_auths}`.
 *
 * **`satisfied` is a lower bound.** An authority can delegate to another account, and
 * following that means fetching *its* authority. This check is offline, so such
 * entries are listed in `unresolvedAccounts` rather than ignored: `satisfied: false`
 * with a non-empty list means "not from these keys alone", not "no". `conclusive`
 * says which.
 */
export declare function checkAuthority(authority: any, publicKeys: Array<string>): AuthorityCheck

/** Decrypt a `#`-prefixed memo with either side's memo key. */
export declare function decodeMemo(wif: string, memo: string): string

/**
 * Encrypt a memo, returning the `#`-prefixed string.
 *
 * The plaintext is written as a Graphene string (varint length, then UTF-8), which is
 * what hive-js, dhive, Keychain and HiveSigner all do.
 */
export declare function encodeMemo(fromWif: string, toPublicKey: string, message: string, nonce?: bigint | undefined | null): string

/** Generate a new BIP-39 mnemonic. */
export declare function generateMnemonic(strength?: number | undefined | null): string

/** Whether a memo field holds an encrypted memo. */
export declare function isEncryptedMemo(memo: string): boolean

/** hived's protocol limits. See [`Limits`]. */
export declare function limits(): Limits

/**
 * The library version.
 * hived's protocol limits, exported so a caller reads them rather than restating them.
 *
 * These are consensus rules, not this addon's policy: exceeding one gets the **whole
 * transaction** refused, not the offending operation. `signTransaction` already
 * enforces every limit below before signing, so they are here for callers who need to
 * stay inside a limit while *building* — chunking a large `custom_json` being the
 * obvious case.
 *
 * Two of them are worth reading the values for rather than assuming:
 *
 * * `maxCustomDataLen` is **8192 inclusive**. hived's own assert message says "must be
 *   less than 8192 bytes" over code that is `<=`, so chunking to "less than 8192"
 *   silently costs a byte of headroom.
 * * `maxCustomOpsPerBlock` is per **account per block**, not per transaction, and it is
 *   shared by everything that broadcasts on that account. Splitting an oversized
 *   payload into chunks and sending them back to back spends the whole budget in one
 *   block — the fix for one limit is a good way to trip the other.
 *
 * ```js
 * const { limits } = require('hivecomb')
 * // chunk by measured bytes, not by item count: the ceiling is a property of your
 * // encoding, not of the protocol, and it moves when the encoding does.
 * if (Buffer.byteLength(json) > limits.maxCustomDataLen) { /* split *\/ }
 * ```
 */
export interface Limits {
  /** Longest `custom_json` id, in bytes. */
  maxCustomIdLen: number
  /** Longest `custom_json` payload or `custom` data, in bytes. Inclusive. */
  maxCustomDataLen: number
  /** Custom operations one **account** may have in a single **block**. */
  maxCustomOpsPerBlock: number
  /** Longest memo, in bytes. */
  maxMemoLen: number
  /** Longest comment title, in bytes. */
  maxTitleLen: number
  /** Longest permlink, in bytes. */
  maxPermlinkLen: number
  /** Entries an authority may hold across `account_auths` and `key_auths` together. */
  maxAuthorityMembership: number
  /** Beneficiaries a comment may name. */
  maxBeneficiaries: number
  /** Longest proposal subject, in bytes. */
  maxProposalSubjectLen: number
  /** Proposal ids one vote or removal may carry. */
  maxProposalIds: number
  /** Longest witness URL, in bytes. */
  maxWitnessUrlLen: number
}

/**
 * Recover the public key that signed a message.
 *
 * Raises unless the signature is well formed. Recovery answers "which key would have
 * produced this?", so a tampered signature recovers a *different* key rather than
 * failing — compare the result, or use `verifyMessage`.
 */
export declare function recoverMessage(message: string | Buffer, signature: string): PublicKey

/** Sign a message with a WIF key, returning hex. */
export declare function signMessage(message: string | Buffer, wif: string): string

/**
 * Build and sign a transaction entirely offline.
 *
 * `operations` is an array of `[name, fields]` pairs. `blockRef` supplies the TaPoS
 * reference — from a `TaposCache`, or `BlockRef.fromBlockId(...)`.
 *
 * Returns an object ready to POST to `network_broadcast_api.broadcast_transaction`,
 * plus the transaction id under `trxId`.
 *
 * No network access happens anywhere in this call.
 */
export declare function signTransaction(operations: string | Array<any>, blockRef: BlockRef, keys: Array<string | PrivateKey>, expirationSeconds?: number | undefined | null, chain?: string | undefined | null): any

/**
 * Build and sign a transaction, returning it as a **JSON string**.
 *
 * Identical work to [`sign_transaction`], and identical bytes — the same signature over
 * the same digest — but it hands back the rendered JSON instead of a JavaScript object.
 *
 * This exists because of what callers do next. A signed transaction's destination is
 * almost always an HTTP body, so the object form is rendered to JSON internally, parsed
 * into an object to cross the boundary, and then serialized straight back to JSON by
 * the caller. Two of those three steps are pure loss, and they scale with the number of
 * operations: at fifty operations the parse alone costs more than the elliptic curve
 * work.
 *
 * Use this when the result is going onto the wire. Use `signTransaction` when the
 * caller needs to inspect or modify the transaction, where the object is worth its
 * price.
 *
 * ```js
 * const trx = hivecomb.signTransactionJson(operations, blockRef, [key])
 * const body = `{"jsonrpc":"2.0","method":"network_broadcast_api.broadcast_transaction",`
 *            + `"params":{"trx":${trx}},"id":1}`
 * ```
 */
export declare function signTransactionJson(operations: string | Array<any>, blockRef: BlockRef, keys: Array<string | PrivateKey>, expirationSeconds?: number | undefined | null, chain?: string | undefined | null): string

/** The digest a transaction would be signed over, without signing it. */
export declare function transactionDigest(operations: string | Array<any>, blockRef: BlockRef, expiration: string, chain?: string | undefined | null): Buffer

/** The transaction id of an unsigned operation set, without signing it. */
export declare function transactionId(operations: string | Array<any>, blockRef: BlockRef, expiration: string): string

/** Validate a BIP-39 mnemonic's checksum and word list. */
export declare function validateMnemonic(mnemonic: string): boolean

/** Verify that `signature` over `message` was made by `publicKey`. */
export declare function verifyMessage(message: string | Buffer, signature: string, publicKey: PublicKey): boolean

export declare function version(): string
