"""Type stubs for the `hivecomb` extension module.

Written because an integrator had to type the module as `object` and hand-roll a
`hasattr` capability check without them. Signatures here are taken from the module's
own `__text_signature__`, not from memory — if they drift, that is a bug in this file.

`Operation` is `(name, fields)`, e.g. `("transfer", {"from": "alice", ...})`. Amounts
are strings like `"1.234 HIVE"`, never floats: a float cannot hold `50000000000.123456`
exactly and the chain is unforgiving about the difference.
"""

from typing import Any, Mapping, Sequence, TypedDict

Operation = tuple[str, Mapping[str, Any]]

# hived's protocol limits, re-exported from the Rust core so callers read them
# rather than restating them. Exceeding one gets the whole transaction refused,
# not the offending operation.
MAX_AUTHORITY_MEMBERSHIP: int
MAX_BENEFICIARIES: int
MAX_CUSTOM_DATA_LEN: int
MAX_CUSTOM_ID_LEN: int
MAX_CUSTOM_OPS_PER_BLOCK: int
MAX_MEMO_LEN: int
MAX_PERMLINK_LEN: int
MAX_PROPOSAL_IDS: int
MAX_PROPOSAL_SUBJECT_LEN: int
MAX_TITLE_LEN: int
MAX_WITNESS_URL_LEN: int
VOTING_MANA_REGENERATION_SECONDS: int

class SignedTransaction(TypedDict):
    ref_block_num: int
    ref_block_prefix: int
    expiration: str
    operations: list[list[Any]]
    extensions: list[Any]
    signatures: list[str]
    trx_id: str

class AuthorityCheck(TypedDict):
    """The three-way answer. `satisfied` alone is not the whole story: when
    `conclusive` is False the authority defers to accounts that were not looked up,
    so "not satisfied" means "not from these keys alone", not "no"."""
    satisfied: bool
    conclusive: bool
    weight: int
    threshold: int
    matched_keys: list[str]
    unresolved_accounts: list[Any]

__version__: str

class PublicKey:
    def __init__(self, key: str) -> None: ...
    def to_hex(self) -> str: ...
    def to_string_with_prefix(self, prefix: str) -> str: ...
    def __str__(self) -> str: ...

class PrivateKey:
    def __init__(self, key: str) -> None: ...
    @staticmethod
    def from_wif(wif: str) -> PrivateKey: ...
    @staticmethod
    def generate() -> PrivateKey: ...
    @staticmethod
    def from_password(account: str, role: str, password: str) -> PrivateKey: ...
    @staticmethod
    def from_brain_key(brain_key: str, sequence: int = ...) -> PrivateKey: ...
    @staticmethod
    def from_mnemonic(
        mnemonic: str, passphrase: str = ..., path: str | None = ...
    ) -> PrivateKey: ...
    @staticmethod
    def from_bip38(encrypted: str, passphrase: str) -> PrivateKey: ...
    def public_key(self) -> PublicKey: ...
    def to_wif(self) -> str: ...
    def to_bip38(self, passphrase: str) -> str: ...
    def sign_message(self, message: str) -> str: ...

class BlockRef:
    @staticmethod
    def from_block_id(block_id: str) -> BlockRef: ...
    @staticmethod
    def from_parts(ref_block_num: int, ref_block_prefix: int) -> BlockRef: ...
    @property
    def ref_block_num(self) -> int: ...
    @property
    def ref_block_prefix(self) -> int: ...
    @property
    def block_num(self) -> int: ...

class TaposCache:
    """A block reference kept fresh out of band, so signing never waits on a node.

    `block_ref` **raises** once the cached value is older than `max_age_seconds`
    rather than returning a stale reference — a stale one produces a transaction the
    relay accepts and the chain rejects, which is a silent failure. Catch the
    exception and refresh; do not treat it as fatal.
    """
    def __init__(self, max_age_seconds: int = ...) -> None: ...
    def store(self, ref_block_num: int, ref_block_prefix: int) -> None: ...
    def store_block_id(self, block_id: str) -> None: ...
    def block_ref(self) -> BlockRef: ...
    def is_fresh(self) -> bool: ...
    def age_seconds(self) -> float | None: ...
    def invalidate(self) -> None: ...

class Wallet:
    """scrypt for the key derivation, AES-256-GCM for the contents. Authenticated, so
    a tampered file fails to open rather than decrypting to garbage."""
    def __init__(self, path: str) -> None: ...
    def create(self, passphrase: str) -> None: ...
    def open(self, passphrase: str) -> None: ...
    def unlock(self, passphrase: str) -> None: ...
    def lock(self) -> None: ...
    def is_locked(self) -> bool: ...
    def add_key(self, wif: str) -> str: ...
    def remove_key(self, public_key: str) -> None: ...
    def get_key(self, public_key: str) -> str: ...
    def get_key_for_role(self, account: str, role: str) -> str: ...
    def public_keys(self) -> list[str]: ...
    def index(self) -> list[str]: ...
    def change_passphrase(self, old: str, new: str) -> None: ...

def sign_transaction(
    operations: Sequence[Operation],
    block_ref: BlockRef,
    wifs: Sequence[str],
    expiration_seconds: int = ...,
    chain: str | None = ...,
) -> SignedTransaction:
    """Build and sign entirely offline. No network call is made."""
    ...

def transaction_digest(
    operations: Sequence[Operation],
    block_ref: BlockRef,
    expiration: str,
    chain: str | None = ...,
) -> bytes:
    """`sha256(chain_id || serialized_tx)` — deterministic, and where every
    serialization bug lives. The right thing to compare against another
    implementation; signature bytes are not, since any canonical signature is valid."""
    ...

def transaction_id(
    operations: Sequence[Operation],
    block_ref: BlockRef,
    expiration: str,
    chain: str | None = ...,
) -> str: ...
def sign_message(message: str, wif: str) -> str: ...
def verify_message(message: str, signature: str, public_key: PublicKey) -> bool:
    """Returns the answer — check it. beem's equivalent computed a tautology and
    discarded the result."""
    ...

def recover_message(message: str, signature: str) -> PublicKey: ...
def recover_digest(digest: bytes, signature: str) -> PublicKey: ...
def encode_memo(
    from_wif: str, to_public_key: str, message: str, nonce: int | None = ...
) -> str: ...
def decode_memo(wif: str, memo: str) -> str: ...
def is_encrypted_memo(memo: str) -> bool: ...
def check_authority(
    authority: Mapping[str, Any], public_keys: Sequence[str]
) -> AuthorityCheck: ...
def generate_mnemonic(strength: int = ...) -> str: ...
def validate_mnemonic(mnemonic: str) -> bool: ...
def chain_id(chain: str | None = ...) -> str:
    """The chain id this build signs against, as hex. A compile-time constant — there
    is no code path that falls back to another value, which is the failure mode that
    produced signatures valid on no chain."""
    ...

def operation_names() -> list[str]:
    """Every operation name in id order: `operation_names()[n]` has id `n`."""
    ...
